### ISSUE TITLE
Report builder error on scenario outline

### ISSUE THREAD

**Issue by allistairpoon** [Substeps/substeps-framework#53]
Run scenario outline with a table with more then one row.

Failed to execute goal org.substeps:substeps-maven-plugin:1.0.6-SNAPSHOT:build-report

java.util.NoSuchElementException

**Comment by iantmoore** [comment]
caused by the outline not having a dynamic name, each row in the outline attempted to create the same results filename, overwriting the previous results file - ending up with the failure above.
